export class Localization
{
    localization: any = [
        {
            no: 'No',
            yes: 'Yes',
            host: 'Host',
            port: 'Port',
            error: 'Error',
            total: 'Total',
            arabic: 'Arabic',
            server: 'Server',
            signIn: 'Sign In',
            english: 'English',
            success: 'Success',
            connect: 'Connect',
            language: 'Language',
            settings: 'Settings',
            invoices: 'Invoices',
            password: 'Password',
            protocol: 'Protocol',
            issuerName: 'Issuer',
            userName: 'User Name',
            clientId: 'Client Id',
            validEInvoice: 'Valid',
            fieldName: 'Field Name',
            fieldIsArray: 'Is Array',
            failedEInvoice: 'Failed',
            receiverName: 'Receiver',
            debitNotes: 'Debit Notes',
            internalId: 'Internal ID',
            totalSales: 'Total Sales',
            netAmount: 'Total Amount',
            fieldDataType: 'Data Type',
            invalidEInvoice: 'Invalid',
            uuid: 'Unique Document Id',
            creditNotes: 'Credit Notes',
            userSchema: 'User / Schema',
            serviceName: 'Service Name',
            isRequired: ' is required.',
            rejectedEInvoice: 'Rejected',
            clientSecret: 'Client Secret',
            loginFormName: 'Sign In Form',
            submittedEInvoice: 'Submitted',
            cancelledEInvoice: 'Cancelled',
            invalidClient: 'Invalid Client',
            fieldDescreption: 'Descreption',
            dateTimeIssued: 'Issuance Date',
            totalDiscount: 'Total Discount',
            dateTimeReceived: 'Receive Date',
            hostReequired: 'Host is required.',
            portReequired: 'Port is required.',
            fieldValueExample: 'Value Example',
            longId: 'Unique Long Temporary Id',
            fieldIsRequired: 'Is Field Required',
            serverReequired: 'Server is required.',
            userConfiguration: 'Users Configuration',
            passwordReequired: 'Password is required.',
            protocolReequired: 'Protocol is required.',
            clientIdReequired: 'Client id is required.',
            fieldDatabaseObjectName: 'Database Object Name',
            fieldDatabaseColumnName: 'Database Column Name',
            branchesConfiguration: 'Branches Configuration',
            submissionUUID: 'Unique Document Submission Id',
            eInvoiceConfiguration: 'E-Invoice Configuration',
            posConfiguration: 'Point Of Sales Configuration',
            eReceiptConfiguration: 'E-Receipt Configuration',
            userSchemaReequired: 'User / Schema is required.',
            serviceNameReequired: 'Service Name is required.',
            fieldIsStructureDataType: 'Is Structure Data Type',
            clientSecretReequired: 'Client secret is required.',
            successConnectDatabase: ' connect to the database.',
            failConnectDatabase: ' in connection with the database.',
            userPermissionsConfiguration: 'User Permissions Configuration',
            
            sales: 'Sales',
            purchases: 'Purchases',
            eReceipt: 'Receipt',
            eReturnReceipt: 'Return Receipt',
            issuerId: 'Issuer Id',
            receiverId: 'Receiver Id',
            fromDateTimeIssued: 'From Issued Date',
            toDateTimeIssued: 'To Issued Date',
            fromDateTimeReceived: 'From Received Date',
            toDateTimeReceived: 'To Received Date',
            paymentMethod: 'Payment Method',
            receiptNumber: 'Receipt Number',
            submissionChannel: 'Submission Channel',
            
            deviceSerialNumber: 'Device Serial Number',
            receiverRegisterationNumber: 'Receiver Registeration Number',
            direction: 'Direction',
            search: 'Search',
            currency: 'Currency',
            exchangeRate: 'Exchange Rate',
            
        },
        {
            no: 'لا',
            yes: 'نعم',
            host: 'مضيف',
            port: 'رقم المخرج',
            error: 'خطأ',
            total: 'الإجمالى',
            arabic: 'العربية',
            server: 'الخادم',
            signIn: 'تسجيل الدخول',
            english: 'الانجليزيه',
            success: 'تم',
            connect: 'إتصال',
            language: 'اللغة',
            settings: 'تهيئة النظام',
            invoices: 'الفواتير',
            password: 'كلمة المرور',
            protocol: 'البرتوكول',
            issuerName: 'البائع',
            userName: 'إسم المستخدم',
            clientId: 'كود العميل',
            validEInvoice: 'صحيح',
            fieldName: 'إسم الحقل',
            fieldIsArray: 'هل هو مصفوفه',
            failedEInvoice: 'فاشلة',
            receiverName: 'المشترى',
            debitNotes: 'مذكرات مدين',
            internalId: 'الرقم الداخلى',
            totalSales: 'اجمالي المبيعات',
            netAmount: 'اجمالي المبلغ',
            fieldDataType: 'نوع الحقل',
            invalidEInvoice: 'غير صحيح',
            uuid: 'كود المستند الفريد',
            creditNotes: 'مذكرات دائن',
            userSchema: 'المستخدم / المخطط',
            serviceName: 'إسم الخدمة',
            isRequired: ' مطلوب ',
            rejectedEInvoice: 'مرفوض',
            clientSecret: 'رمز العميل التشفيرى',
            loginFormName: 'شاشة تسجيل الدخول',
            submittedEInvoice: 'مُقَدَّم',
            cancelledEInvoice: 'ألغيت',
            invalidClient: 'عميل غير صالح',
            fieldDescreption: 'التوصيف',
            dateTimeIssued: 'تاريخ الإصدار',
            totalDiscount: 'اجمالي الخصم',
            dateTimeReceived: 'تاريخ الإستلام',
            hostReequired: 'قيمة حقل المضيف مطلوب.',
            portReequired: 'قيمة حقل رقم المخرج مطلوب.',
            fieldValueExample: 'مثال لقيمة الحقل',
            longId: 'كود مؤقت طويل فريد',
            fieldIsRequired: 'هل الحقل إجبارى',
            serverReequired: 'قيمة حقل الخادم مطلوب.',
            userConfiguration: 'تهيئة المستخدمين',
            passwordReequired: 'قيمة حقل كلمة المرور مطلوب.',
            protocolReequired: 'قيمة حقل البروتوكول مطلوب.',
            clientIdReequired: 'قيمة حقل كود العميل مطلوب.',
            fieldDatabaseObjectName: 'إسم عنصر قاعدة البيانات',
            fieldDatabaseColumnName: 'إسم عمود قاعدة البيانات',
            branchesConfiguration: 'تهيئة الفروع',
            submissionUUID: 'كود تقديم المستند',
            eInvoiceConfiguration: 'تهيئة الفاتورة الالكترونية',
            posConfiguration: 'تهيئة نقاط البيع',
            eReceiptConfiguration: 'تهيئة الايصال الالكترونى',
            userSchemaReequired: 'قيمة حقل المستخدم / المخطط مطلوب.',
            serviceNameReequired: 'قيمة حقل إسم الخدمة مطلوب.',
            fieldIsStructureDataType: 'هل الحقل من النوع الهيكلى',
            clientSecretReequired: 'قيمة حقل رمز العميل التشفيرى مطلوب.',
            successConnectDatabase: ' الاتصال بقاعدة البيانات بنجاح.',
            failConnectDatabase: ' فى الاتصال بقاعدة البيانات.',
            userPermissionsConfiguration: 'تهيئة صلاحيات المستخدمين',

            
            sales: 'المبيعات',
            purchases: 'المشتريات',
            eReceipt: 'الايصال الالكترونى',
            eReturnReceipt: 'مرتجع الايصال الالكترونى',
            
            issuerId: 'كود البائع',
            receiverId: 'كود المشترى',
            fromDateTimeIssued: 'من تاريخ بيع',
            toDateTimeIssued: 'الى تاريخ بيع',
            fromDateTimeReceived: 'من تاريخ شراء',
            toDateTimeReceived: 'الى تاريخ شراء',
            paymentMethod: 'طريقة الدفع',
            receiptNumber: 'رقم الايصال',
            submissionChannel: 'قناة التقديم',
            
            deviceSerialNumber: 'الرقم التسلسلى للجهاز',
            receiverRegisterationNumber: 'رقم تسجيل المشترى',
            direction: 'الاتجاه',
            search: 'بحث',

            currency: 'العملة',
            exchangeRate: 'معامل التحويل',
            
        }
    ];
}